set myConnectionString to {type:"Excel", file:ResourcePath("ConsentForms.xlsx"),writeable:true}
put the number of records of myConnectionString into recordCount
put recordCount

repeat with each item myCurrentRecord of (each of the records of myConnectionString)
	put {
		myProcedureTitle: myCurrentRecord.ProcedureTitle,
		myProcedureSubtitle: myCurrentRecord.ProcedureSubtitle,
		myPatientName: myCurrentRecord.PatientFirstName && myCurrentRecord.PatientLastName,
		myProcedureDate: myCurrentRecord.ProcedureDate,
		myProviderNameAndTitle: myCurrentRecord.ProviderNameAndTitle,
		myProviderPhone: myCurrentRecord.ProviderPhone,
		myProviderPronoun1: item 1 of (myCurrentRecord.ProviderPronoun split by "|"),
		myProviderPronoun2: item 2 of (myCurrentRecord.ProviderPronoun split by "|")
	} into myReplacementList


	Log "Creating a consent form for" && myCurrentRecord.PatientFirstName && myCurrentRecord.PatientLastName
	put trimall(merge("Consent form for [[myCurrentRecord.PatientFirstName]] [[myCurrentRecord.PatientLastName]]_[[myCurrentRecord.ProcedureTitle]]_[[myCurrentRecord.ProcedureDate]]"),"*/") into myFileName
	put file ResourcePath("consent_letter_template_singlepage.html") into myTempFile
	repeat with each myCurrentReplacement in the keys of myReplacementList
		log myReplacementList.(myCurrentReplacement)
		replace every instance of myCurrentReplacement in myTempFile with myReplacementList.(myCurrentReplacement)
	end repeat
	put myTempFile into file ResourcePath(myFileName&".html")
end repeat